# Generated by Django 4.2.16 on 2024-10-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=100, unique=True)),
                ('address', models.CharField(blank=True, help_text='Company address', max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, help_text='Branch name', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='User is a manager'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company'),
        ),
    ]
