# Generated by Django 4.2.16 on 2024-10-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='no_of_shifts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
