# Generated by Django 4.2.16 on 2024-10-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_no_of_shifts_customuser_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_shifts_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
